services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/api
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/usr/src/client
    command: npm start
