services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/api
    environment:
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/usr/src/client
    command: npm start
